
title: Xuan Feng's Homepage ðŸ°
author: Riccardo Graziosi 
description: >  my resume.
theme: riggraz/no-style-please

theme_config:
  appearance: "auto" 
  back_home_text: ".." 
  date_format: "%Y-%m-%d"
  show_description: false 

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
