
title: Xuan Feng's Homepage ðŸ°
author: Riccardo Graziosi # name of site's author
description: >  my resume.


# favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
